### ISSUE TITLE
Who can hack evowars on crazygames PC on please

### ISSUE THREAD

**Issue by buddha-3979** [Robot1w/Blooket-Cheats-That-Work#3]
Who can hack evowars on crazygames on PC please
I need a gui and make them can hack evowars on crazygames on pc example : set rank ; set xp ; toggle month wing ; toggle week wing ; toggle day wing in general who can hack evowars on crazygames on PC pleaseeee?

**Comment by BlooketCommunity** [comment]
![image](https://github.com/user-attachments/assets/d6a03465-199c-4ce5-90d8-6f35a7b4f3d3)

dont get me to write to @TheAmazingAceLeo (https://github.com/Blooket-Council/Blooket-Cheats/issues/4)
